project_id = "upr-2026"

[auth]
enable_signup = false

[functions.create-order]
verify_jwt = false
[functions.create-mercadopago-preference]
verify_jwt = false
[functions.mercadopago-webhook]
verify_jwt = false
[functions.order-status]
verify_jwt = false
[functions.reconcile-order]
verify_jwt = false
